// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wasp.WebApi.Data;

#nullable disable

namespace wasp.WebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211202150321_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("wasp.WebApi.Data.Models.DataItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    b.Property<string>("DataTableId")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DataTableId")
                        .HasColumnOrder(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("Name")
                        .HasColumnOrder(2);

                    b.Property<string>("PythonId")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PythonId")
                        .HasColumnOrder(3);

                    b.HasKey("Id", "DataTableId");

                    b.HasIndex("DataTableId");

                    b.ToTable("DataItem");
                });

            modelBuilder.Entity("wasp.WebApi.Data.Models.DataTable", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Name")
                        .HasColumnOrder(1);

                    b.Property<string>("SqlId")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("SqlId")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable("DataTable");
                });

            modelBuilder.Entity("wasp.WebApi.Data.Models.Index", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint")
                        .HasColumnName("Type")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.ToTable("Index");
                });

            modelBuilder.Entity("wasp.WebApi.Data.Models.Relation", b =>
                {
                    b.Property<string>("IndexId")
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("IndexId")
                        .HasColumnOrder(0);

                    b.Property<string>("KeyDataItemId")
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("KeyDataItemId")
                        .HasColumnOrder(1);

                    b.Property<string>("KeyDataTableId")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("KeyDataTableId")
                        .HasColumnOrder(2);

                    b.Property<string>("ReferenceDataItemId")
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("ReferenceDataItemId")
                        .HasColumnOrder(3);

                    b.Property<string>("ReferenceDataTableId")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ReferenceDataTableId")
                        .HasColumnOrder(4);

                    b.HasKey("IndexId", "KeyDataItemId", "KeyDataTableId");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("IndexId", "KeyDataItemId", "KeyDataTableId"), false);

                    b.HasIndex("KeyDataItemId", "KeyDataTableId");

                    b.HasIndex("ReferenceDataItemId", "ReferenceDataTableId");

                    b.ToTable("Relation");
                });

            modelBuilder.Entity("wasp.WebApi.Data.Models.DataItem", b =>
                {
                    b.HasOne("wasp.WebApi.Data.Models.DataTable", "DataTable")
                        .WithMany()
                        .HasForeignKey("DataTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataTable");
                });

            modelBuilder.Entity("wasp.WebApi.Data.Models.Relation", b =>
                {
                    b.HasOne("wasp.WebApi.Data.Models.Index", "Index")
                        .WithMany()
                        .HasForeignKey("IndexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wasp.WebApi.Data.Models.DataItem", "KeyDataItem")
                        .WithMany("KeyRelations")
                        .HasForeignKey("KeyDataItemId", "KeyDataTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wasp.WebApi.Data.Models.DataItem", "ReferenceDataItem")
                        .WithMany("ReferenceRelations")
                        .HasForeignKey("ReferenceDataItemId", "ReferenceDataTableId");

                    b.Navigation("Index");

                    b.Navigation("KeyDataItem");

                    b.Navigation("ReferenceDataItem");
                });

            modelBuilder.Entity("wasp.WebApi.Data.Models.DataItem", b =>
                {
                    b.Navigation("KeyRelations");

                    b.Navigation("ReferenceRelations");
                });
#pragma warning restore 612, 618
        }
    }
}
