// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wasp.WebApi.Data;

#nullable disable

namespace wasp.WebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230318215847_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("wasp.WebApi.Data.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ApplicationRole")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUser", "data");
                });

            modelBuilder.Entity("wasp.WebApi.Data.Models.System.DatabaseSchema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasColumnOrder(0)
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Name")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.ToTable("DatabaseSchema", "system");
                });

            modelBuilder.Entity("wasp.WebApi.Data.Models.System.DataItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasColumnOrder(0)
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<string>("ClrName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClrType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColumnName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComputedSql")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DataTableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DatabaseType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasValueRange")
                        .HasColumnType("bit");

                    b.Property<bool>("IsForeignKey")
                        .HasColumnType("bit");

                    b.Property<bool>("IsKey")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNullable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimaryKey")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUniqueIndex")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("Precision")
                        .HasColumnType("int");

                    b.Property<int?>("Scale")
                        .HasColumnType("int");

                    b.Property<string>("ValueRange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Virtual")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DataTableId");

                    b.ToTable("DataItem", "system");
                });

            modelBuilder.Entity("wasp.WebApi.Data.Models.System.DataTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasColumnOrder(0)
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<string>("ClrName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DatabaseSchemaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DatabaseSchemaId");

                    b.ToTable("DataTable", "system");
                });

            modelBuilder.Entity("wasp.WebApi.Data.Models.System.Relationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasColumnOrder(0)
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Relationship", "system");
                });

            modelBuilder.Entity("wasp.WebApi.Data.Models.System.RelationshipDataItem", b =>
                {
                    b.Property<Guid>("RelationshipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SourceDataItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetDataItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RelationshipId", "SourceDataItemId", "TargetDataItemId");

                    b.HasIndex("SourceDataItemId");

                    b.HasIndex("TargetDataItemId");

                    b.ToTable("RelationshipDataItem", "system");
                });

            modelBuilder.Entity("wasp.WebApi.Data.Models.System.DataItem", b =>
                {
                    b.HasOne("wasp.WebApi.Data.Models.System.DataTable", "DataTable")
                        .WithMany("DataItems")
                        .HasForeignKey("DataTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataTable");
                });

            modelBuilder.Entity("wasp.WebApi.Data.Models.System.DataTable", b =>
                {
                    b.HasOne("wasp.WebApi.Data.Models.System.DatabaseSchema", "DatabaseSchema")
                        .WithMany()
                        .HasForeignKey("DatabaseSchemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatabaseSchema");
                });

            modelBuilder.Entity("wasp.WebApi.Data.Models.System.RelationshipDataItem", b =>
                {
                    b.HasOne("wasp.WebApi.Data.Models.System.Relationship", "Relationship")
                        .WithMany("RelationshipDataItems")
                        .HasForeignKey("RelationshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("wasp.WebApi.Data.Models.System.DataItem", "SourceDataItem")
                        .WithMany("TargetRelations")
                        .HasForeignKey("SourceDataItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("wasp.WebApi.Data.Models.System.DataItem", "TargetDataItem")
                        .WithMany("SourceRelations")
                        .HasForeignKey("TargetDataItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Relationship");

                    b.Navigation("SourceDataItem");

                    b.Navigation("TargetDataItem");
                });

            modelBuilder.Entity("wasp.WebApi.Data.Models.System.DataItem", b =>
                {
                    b.Navigation("SourceRelations");

                    b.Navigation("TargetRelations");
                });

            modelBuilder.Entity("wasp.WebApi.Data.Models.System.DataTable", b =>
                {
                    b.Navigation("DataItems");
                });

            modelBuilder.Entity("wasp.WebApi.Data.Models.System.Relationship", b =>
                {
                    b.Navigation("RelationshipDataItems");
                });
#pragma warning restore 612, 618
        }
    }
}
